apiVersion: apps/v1
kind: Deployment
namespace: qa
metadata:
  name: qa
  labels:
    app: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qa
  template:
    metadata:
      labels:
        app: qa
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
