apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/training"   # Ensure this path points correctly to your environment configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
