apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: <environment-name>
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/training/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
